# Generated by Django 2.0.2 on 2018-02-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='pub_date',
        ),
    ]
